# -*- coding: utf-8 -*-
"""digitalsys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PML90nLEyctrYo6DbHwCqKZuog2GWWJs
"""

a_list = [30,28,28,16,14,14,12,10]

#printing my list
print("Main list before remove duplicates: " +str(a_list))


def removeDuplicates():
  res = [] 
  for i in a_list: 
    if i not in res: 
        res.append(i) 
  # printing list after removal  
  print ("The list after removing duplicates : " + str(res)) 

print()
#calling func removeDuplicates
removeDuplicates()


def sortList():
  a_new_list = [30,28,16,14,12,10]
  a_new_list.sort() 
  print("The new sorted list is : "+str(a_new_list))

print()
#calling func for sorting
sortList()
print()



#create dict
a_dict = {"h":30,"g":28,"f":28,"e":16,"d":14,"c":14,"b":12,"a":10}
print("Main dict before edit: " +str(a_dict))


def removeDictDuplicates():
  result = {}
  for key,value in a_dict.items():
    if value not in result.values():
        result[key] = value
  print("The dict with remove duplicate : "+str(result))


print()
#calling func for remove duplicates in dict
removeDictDuplicates()


def sortDictValue():
  a_new_dict = {'h': 30, 'g': 28, 'e': 16, 'd': 14, 'b': 12, 'a': 10}
  print("Sorted dict by value")
  for key in sorted(a_new_dict.keys()):
    print("%s: %s" % (key, a_new_dict[key]))


print()
#print sorting for dict
sortDictValue()


def sortDictKey():
  a_new_dict = {'h': 30, 'g': 28, 'e': 16, 'd': 14, 'b': 12, 'a': 10}
  print("Sorted dict by key")
  for key, value in sorted(a_new_dict.items(), key=lambda item: item[1]):
    print("%s: %s" % (key, value))


print()
#print
sortDictKey()